### ISSUE TITLE
niftycloud_fw failed special ip_protocol

### ISSUE THREAD

**Issue by heriet** [NIFTYCloud/ansible-role-niftycloud#38]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

niftycloud_fw failed when special ip_protocol like 'SSH' and maybe others.

##### STEPS TO REPRODUCE

I create task like these.

```
- name: create fw
  local_action:
    module: niftycloud_fw
    access_key: "<ACCESS_KEY>"
    secret_access_key: "<SECRET_ACCESS_KEY>"
    endpoint: "east-1.cp.cloud.nifty.com"
    group_name: "ansibletestfw"
    availability_zone: "east-14"
    ip_permissions:
      - ip_protocol: "SSH"
        in_out: "IN"
        cidr_ip: "10.0.0.11"
    state: "present"
```

```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "changed_attributes": {}, 
    "created": true, 
    "current_info": {
        "description": "None", 
        "group_name": "ansibletestfw", 
        "ip_permissions": [
            {
                "cidr_ip": "10.0.0.11", 
                "from_port": 22, 
                "group_name": null, 
                "in_out": "IN", 
                "ip_protocol": "TCP", 
                "to_port": 22
            }
        ], 
        "log_limit": 1000
    }, 
    "current_method": "authorize_security_group", 
    "current_state": "present", 
    "failed": true, 
    "group_name": "ansibletestfw", 
    "invocation": {
        "module_args": {
            "access_key": "<ACCESS_KEY>", 
            "availability_zone": "east-14", 
            "description": null, 
            "endpoint": "east-1.cp.cloud.nifty.com", 
            "group_name": "ansibletestfw", 
            "ip_permissions": [
                {
                    "cidr_ip": "10.0.0.11", 
                    "in_out": "IN", 
                    "ip_protocol": "SSH"
                }
            ], 
            "log_limit": null, 
            "purge_ip_permissions": true, 
            "secret_access_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present"
        }, 
        "module_name": "niftycloud_fw"
    }, 
    "msg": "changes failed", 
    "status": -1
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```

`ip_protocol` like `SSH` is converted `TCP` on computing API response.

We need fix `contains_ip_permissions` in niftycloud_fw.py.
